<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.23" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Messages\RepositoryMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RepositoryMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Messages\RepositoryMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>RepositoryMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>