<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <UserSecretsId>540db5be-b2a8-4c4d-ace3-5761b60b3c97</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Cors" Version="5.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.23" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\Service.Abstraction\Service.Abstraction.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>
</Project>